version: '3'

services:

  client:
    image: memories-client-dev
    container_name: client_container
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 4200:4200
    volumes:
      - ./client:/app

  api:
    image: memories-api-dev
    container_name: api_container
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - MONGO_USER
      - MONGO_PASS
      - S3_BUCKET_URL
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
