version: '3'

services:

  # Frontend + Nginx
  client:
    image: memories-client
    container_name: client_container
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
      - 4200:4200
    volumes:
      - ./nginx:/etc/nginx/memories

  # Backend
  api:
    image: memories-api-dev
    container_name: api_container
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - MONGO_USER
      - MONGO_PASS
      - S3_BUCKET_URL
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
