version: '3'

services:
  api:
    image: memories-api-dev
    container_name: api_container
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - ./api:/app

  mongo:
    image: mongo
    container_name: mongo_container
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    container_name: mongo_express_container
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
