version: '3'

services:
  api:
    image: memories-api-dev
    container_name: api_container
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
